<!DOCTYPE html>
<html lang="en">

<?php require_once INITIALS . 'header.phtml'; ?>

<body class="sb-nav-fixed">
    <?php require_once INITIALS . 'nav.phtml'; ?>

    <div id="layoutSidenav">
    <?php require_once INITIALS . 'sidebare.phtml'; ?>
        <div id="layoutSidenav_content">
            <main>
                <?php echo $page_body; ?>
            </main>
            <?php require_once INITIALS . 'footer.phtml'; ?>
        </div>
    </div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="<?php echo URL_ROOT ?>/assets/demo/chart-area-demo.js"></script>
        <script src="<?php echo URL_ROOT ?>/assets/demo/chart-bar-demo.js"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
        <script src="<?php echo URL_ROOT ?>/assets/demo/datatables-demo.js"></script>
</body>
</html>