<div class="card mb-4 mt-5">
                            <div class="card-header">
                                <i class="fas fa-table mr-1"></i>
                                Livres
                            </div>
                            
                            <div class="card-body">
    <div class="table-responsive">
    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Nom Livre</th>
                    <th>Auteur</th>
                </tr>
            </thead>
        </table>
    </div>
</div>
</div>