<div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>
                            <a class="nav-link" href="<?= URL_ROOT ?>">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Acceuil
                            </a>
                            
                            <div class="sb-sidenav-menu-heading">Addons</div>
                            <a class="nav-link" href="<?= URL_ROOT ?>/Livre">
                                <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                                Livre
                            </a>
                            <a class="nav-link" href="<?= URL_ROOT ?>/Auteur">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                Auteur
                            </a>
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        Malo
                    </div>
                </nav>
            </div>