<div class="card mb-4 mt-5">
                            <div class="card-header">
                                <i class="fas fa-table mr-1"></i>
                                Nouveau Auteur
                            </div>
                            
                            <div class="card-body">
    <div class="table-responsive">

    <div class="col-md-12 text-right">
    <a href="<?= URL_ROOT?>/auteur/" class="btn btn-primary"> auteur</a>
    </div>
    <?= (isset($data['ERROR'])) ? '<div class="alert alert-danger col-md-8">'.$data['ERROR'].'</div>' : '' ?>
    <form action="<?= URL_ROOT ?>/auteur/create" method="post" class="container row">
        <div class="col-md-3">
            <label for="">Nom autheur</label>
            <input type="text" name="nomauteur" id="" class="form-control" value="<?= (isset($data['nomauteur'])) ? $data['nomauteur'] : '' ?>" >
        </div>
        <div class="col-md-3">
            <label for="">adresse</label>
            <input type="text" name="adresse" id="" class="form-control" value="<?= (isset($data['adresse'])) ? $data['adresse'] : '' ?>" >
        </div>
        <div class="col-md-3">
            <label for="">telephone</label>
            <input type="text" name="telephone" id="" class="form-control" value="<?= (isset($data['telephone'])) ? $data['telephone'] : '' ?>" >
        </div>
        <div class="col-md-3">
            <label for=""></label><br>
            <button type="submit" class="btn btn-info"> Enregistrer</button>
        </div>
     </form>
    </div>
</div>
</div>