<div class="card mb-4 mt-5">
                            <div class="card-header">
                                <i class="fas fa-table mr-1"></i>
                                Autheur
                            </div>
                            
                            <div class="card-body">
    <div class="table-responsive">

    <div class="col-md-12 text-right">
    <a href="<?= URL_ROOT?>/auteur/create" class="btn btn-primary">Ajout auteur</a>
    </div>
    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Nom Auteur</th>
                    <th>Adresse</th>
                    <th>Telephone</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($data as $auteur) {  ?>
                    <tr>
                        <td><?= $auteur->nomauteur ?></td>
                        <td><?= $auteur->adresse ?></td>
                        <td><?= $auteur->telephone ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>
</div>